# Generated by Django 2.1.5 on 2020-06-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='prize',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='prize',
            new_name='price',
        ),
    ]
